import { ethers } from 'ethers';
import dotenv from 'dotenv';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { compileContracts } from './compile-contracts.js';
import { DEPLOYED_ADDRESSES } from '../config/deployed-addresses.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, '../..');

dotenv.config({ path: path.join(rootDir, '.env') });

export async function deployUpdatedPool() {
  console.log('========================================================================');
  console.log('SANAD PROTOCOL — DEPLOY UPDATED SANADLIQUIDITYPOOL TO CC3 TESTNET');
  console.log('Includes verifyAndRecordReturnDistribution & ReturnDistributionVerified');
  console.log('========================================================================\n');

  const privateKey = process.env.CREDITCOIN_PRIVATE_KEY || process.env.PRIVATE_KEY;
  if (!privateKey) {
    throw new Error('Valid funded PRIVATE_KEY not found in backend/.env');
  }

  const cc3Rpc = process.env.CREDITCOIN_RPC_URL || 'https://rpc.cc3-testnet.creditcoin.network';
  const cc3Provider = new ethers.JsonRpcProvider(cc3Rpc, 102031, {
    staticNetwork: ethers.Network.from(102031),
  });
  const cc3Signer = new ethers.Wallet(privateKey, cc3Provider);

  console.log(`• Deployer: ${cc3Signer.address}`);
  const balance = await cc3Provider.getBalance(cc3Signer.address);
  console.log(`• CC3 Balance: ${ethers.formatEther(balance)} tCTC\n`);

  console.log('[1/5] Compiling smart contracts...');
  const compiled = compileContracts();

  const sagTokenAddress = DEPLOYED_ADDRESSES.cc3.sagToken;
  const repaymentGatewayAddress = DEPLOYED_ADDRESSES.sepolia.repaymentGateway;
  const investorVaultAddress = DEPLOYED_ADDRESSES.sepolia.investorVault;

  console.log(`\n[2/5] Deploying SanadLiquidityPool with sagToken: ${sagTokenAddress}...`);
  const poolFactory = new ethers.ContractFactory(
    compiled.SanadLiquidityPool.abi,
    compiled.SanadLiquidityPool.bytecode,
    cc3Signer
  );
  const poolContract = await poolFactory.deploy(sagTokenAddress);
  console.log(`  • Broadcast Tx: ${poolContract.deploymentTransaction()?.hash}`);
  await poolContract.waitForDeployment();
  const newPoolAddress = await poolContract.getAddress();
  console.log(`  ✅ New SanadLiquidityPool deployed at: ${newPoolAddress}`);
  console.log(`     Explorer: https://creditcoin-testnet.blockscout.com/address/${newPoolAddress}`);

  console.log('\n[3/5] Configuring AccessControl Roles on SAGToken...');
  const sagContract = new ethers.Contract(sagTokenAddress, compiled.SAGToken.abi, cc3Signer);
  const SETTLEMENT_ROLE = ethers.keccak256(ethers.toUtf8Bytes('SETTLEMENT_ROLE'));

  const grantTx = await (sagContract as any).grantRole(SETTLEMENT_ROLE, newPoolAddress);
  console.log(`  • Broadcast grantRole Tx: ${grantTx.hash}`);
  await grantTx.wait();
  console.log(`  ✅ Granted SETTLEMENT_ROLE to new SanadLiquidityPool`);

  console.log('\n[4/5] Configuring Gateway Addresses on new SanadLiquidityPool...');
  const gwTx = await (poolContract as any).setRepaymentGatewayAddress(repaymentGatewayAddress);
  await gwTx.wait();
  console.log(`  ✅ RepaymentGateway set: ${repaymentGatewayAddress} (Tx: ${gwTx.hash})`);

  const vaultTx = await (poolContract as any).setInvestorVaultAddress(investorVaultAddress);
  await vaultTx.wait();
  console.log(`  ✅ InvestorVault set: ${investorVaultAddress} (Tx: ${vaultTx.hash})`);

  console.log('\n[5/5] Depositing Initial Liquidity (10 tCTC)...');
  const depositTx = await (poolContract as any).depositLiquidity({ value: ethers.parseEther('10.0') });
  await depositTx.wait();
  console.log(`  ✅ Deposited 10 tCTC liquidity into pool (Tx: ${depositTx.hash})`);

  // Update backend/src/config/deployed-addresses.ts
  const configPath = path.resolve(rootDir, 'src/config/deployed-addresses.ts');
  const updatedConfig = `/**
 * ============================================================================
 * DEPLOYED CONTRACT ADDRESSES — SINGLE SOURCE OF TRUTH
 * ============================================================================
 * Generated by: backend/src/scripts/deploy-updated-pool.ts
 *
 * Do NOT hardcode contract addresses elsewhere in the codebase.
 * Backend files: import { DEPLOYED_ADDRESSES } from '@/config/deployed-addresses.js';
 * Frontend files: update fallback values to match and add a comment pointing here.
 * Standalone scripts that cannot import: update hardcoded value and add a comment.
 * ============================================================================
 */

export const DEPLOYED_ADDRESSES = {
  // Creditcoin CC3 Testnet (Chain ID: 102031)
  cc3: {
    sagToken: '${sagTokenAddress}',
    liquidityPool: '${newPoolAddress}',
    creditOracle: '${DEPLOYED_ADDRESSES.cc3.creditOracle}',
  },
  // Ethereum Sepolia Testnet (Chain ID: 11155111)
  sepolia: {
    investorVault: '${investorVaultAddress}',
    repaymentGateway: '${repaymentGatewayAddress}',
  },
  // Deployment metadata
  meta: {
    deployedAt: '${new Date().toISOString()}',
    commitHash: 'updated-pool',
    deployer: '${cc3Signer.address}',
  },
} as const;
`;

  fs.writeFileSync(configPath, updatedConfig);
  console.log(`\n✅ Updated ${configPath}`);

  // Update backend/.env
  const backendEnvPath = path.resolve(rootDir, '.env');
  if (fs.existsSync(backendEnvPath)) {
    let envContent = fs.readFileSync(backendEnvPath, 'utf8');
    envContent = envContent.replace(
      /SANAD_LIQUIDITY_POOL_ADDRESS="0x[0-9a-fA-F]+"/,
      `SANAD_LIQUIDITY_POOL_ADDRESS="${newPoolAddress}"`
    );
    fs.writeFileSync(backendEnvPath, envContent);
    console.log(`✅ Updated ${backendEnvPath}`);
  }

  // Update frontend fallback in frontend/lib/contracts/sanad-liquidity-pool.ts
  const frontendContractPath = path.resolve(rootDir, '../frontend/lib/contracts/sanad-liquidity-pool.ts');
  if (fs.existsSync(frontendContractPath)) {
    let content = fs.readFileSync(frontendContractPath, 'utf8');
    content = content.replace(
      /export const SANAD_LIQUIDITY_POOL_ADDRESS =\s*process\.env\.NEXT_PUBLIC_SANAD_LIQUIDITY_POOL_ADDRESS \|\|\s*process\.env\.NEXT_PUBLIC_LIQUIDITY_POOL_ADDRESS \|\|\s*'0x[0-9a-fA-F]+';/,
      `export const SANAD_LIQUIDITY_POOL_ADDRESS =\n  process.env.NEXT_PUBLIC_SANAD_LIQUIDITY_POOL_ADDRESS ||\n  process.env.NEXT_PUBLIC_LIQUIDITY_POOL_ADDRESS ||\n  '${newPoolAddress}';`
    );
    fs.writeFileSync(frontendContractPath, content);
    console.log(`✅ Updated ${frontendContractPath}`);
  }

  // Update frontend/.env.local
  const frontendEnvPath = path.resolve(rootDir, '../frontend/.env.local');
  if (fs.existsSync(frontendEnvPath)) {
    let fEnvContent = fs.readFileSync(frontendEnvPath, 'utf8');
    fEnvContent = fEnvContent.replace(
      /NEXT_PUBLIC_POOL_ADDRESS="0x[0-9a-fA-F]+"/,
      `NEXT_PUBLIC_POOL_ADDRESS="${newPoolAddress}"`
    );
    fEnvContent = fEnvContent.replace(
      /NEXT_PUBLIC_SANAD_LIQUIDITY_POOL_ADDRESS="0x[0-9a-fA-F]+"/,
      `NEXT_PUBLIC_SANAD_LIQUIDITY_POOL_ADDRESS="${newPoolAddress}"`
    );
    fs.writeFileSync(frontendEnvPath, fEnvContent);
    console.log(`✅ Updated ${frontendEnvPath}`);
  }

  console.log('\n========================================================================');
  console.log('🎉 UPDATED SANADLIQUIDITYPOOL DEPLOYMENT COMPLETE');
  console.log(`New Pool Address: ${newPoolAddress}`);
  console.log('========================================================================');

  return { newPoolAddress };
}

if (process.argv[1]?.endsWith('deploy-updated-pool.ts') || process.argv[1]?.endsWith('deploy-updated-pool.js')) {
  deployUpdatedPool()
    .then(() => process.exit(0))
    .catch((err) => {
      console.error('Deployment failed:', err);
      process.exit(1);
    });
}
