/**
 * ============================================================================
 * DEPLOYED CONTRACT ADDRESSES — SINGLE SOURCE OF TRUTH
 * ============================================================================
 * Generated by: backend/src/scripts/deploy-updated-pool.ts
 *
 * Do NOT hardcode contract addresses elsewhere in the codebase.
 * Backend files: import { DEPLOYED_ADDRESSES } from '@/config/deployed-addresses.js';
 * Frontend files: update fallback values to match and add a comment pointing here.
 * Standalone scripts that cannot import: update hardcoded value and add a comment.
 * ============================================================================
 */

export const DEPLOYED_ADDRESSES = {
  // Creditcoin CC3 Testnet (Chain ID: 102031)
  cc3: {
    sagToken: '0x80b9Ae7D0BEfB042a3eb8fDd1af0DCF6E53bEdE9',
    liquidityPool: '0x93C550aABfD0396f9fb2f8a3404E22Eee648Ee05',
    creditOracle: '0x9B926B432bbEFA5405eC9EBB0F7515496c2095a5',
  },
  // Ethereum Sepolia Testnet (Chain ID: 11155111)
  sepolia: {
    investorVault: '0x0e243c2F556eFaDA6352f567AA658b6052F04eD4',
    repaymentGateway: '0x662e21FfB91F35A1f16983e38a9cDAe90f537A80',
  },
  // Deployment metadata
  meta: {
    deployedAt: '2026-09-03T11:45:15.555Z',
    commitHash: 'updated-pool',
    deployer: '0xc7b11732DFba02C96DD7805E98db7E190Cbbc6E9',
  },
} as const;
